apiVersion: v2
appVersion: '1.0'
description: A custom cron with everything needed
name: custom-cron
version: 0.1.0
dependencies:
  - name: common
    repository: https://camptocamp.github.io/helm-common
    version: 0.4.1
